import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

import {colors, fontFamily, fontSize} from '../../comman';

export const styles = StyleSheet.create({
  webViewContainer: {
    flex: 1,
  },
  spacer: {
    width: wp('1%'),
  },
  closButtonContainer: {
    backgroundColor: colors.backgroundColor,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: wp('2%'),
  },
  closeButtonImage: {
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backTextStyle: {
    fontFamily: fontFamily.semiBold,
    color: colors.buttonPrimary,
  },
  topImageContainer: {
    flex: 0.4,
    paddingLeft: 2,
    alignSelf: 'center',
    marginVertical: hp('4%'),
  },
  checkInImageStyle: {
    height: hp('10%'),
    width: wp('20%'),
  },
  socialMediaButtonStyle: {
    width: wp('10%'),
    height: undefined,
    aspectRatio: 1,
    marginLeft: 10,
    marginRight: 10,
  },
  socialsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    margin: 0,
    padding: 0,
  },
  createButton: {
    position: 'absolute',
    width: wp('22%'),
    right: 0,
    bottom: hp('12%'),
  },
  image: {
    height: hp('25%'),
    width: wp('55%'),
  },
  imageIcon1: {
    height: 30,
    width: 34,
  },
  imagesContainerHorizontal: {
    paddingVertical: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  teamsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: wp('1.5%'),
  },
  secondContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp('1%'),
  },
  thirdContainer: {
    flex: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  headingText: {
    fontSize: hp(2.4),
    fontFamily: fontFamily.bold,
    fontWeight: '600',
    paddingHorizontal: 15,
    paddingTop: 30,
  },
  headingText2: {
    fontSize: fontSize.small,
    fontFamily: fontFamily.Saira,
    fontWeight: '600',
    overflow: 'visible',
    color: 'black',
    textAlign: 'center',
  },
  headingText3Container: {
    width: wp('20'),
    height: hp('2'),
    alignSelf: 'center',
    marginTop: 7,
  },
  headingText3: {
    fontSize: fontSize.vSmall,
    fontFamily: fontFamily.black,
    fontWeight: '400',
    lineHeight: 14.4,
    textAlign: 'center',
    color: colors.black,
  },
  headingText4: {
    fontSize: fontSize.xxxtinyH,
    fontFamily: fontFamily.black,
    fontWeight: '600',
    lineHeight: 14.4,
    textAlign: 'center',
    color: colors.greyishColor,
    width: wp('20%'),
  },
  spacer2: {
    width: 10,
  },
  headingTextToday: {
    fontSize: fontSize.xxxtinyH,
    fontFamily: fontFamily.black,
    fontWeight: '600',
    lineHeight: 14.4,
    textAlign: 'center',
    color: colors.buttonPrimary,
  },
  headingTextToday2: {
    fontSize: fontSize.xxxtinyH,
    fontFamily: fontFamily.black,
    fontWeight: '600',
    lineHeight: 14.4,
    textAlign: 'center',
    color: colors.black,
  },
  topContainerText: {
    fontFamily: fontFamily.regular,
    fontWeight: '400',
    fontSize: 8,
    lineHeight: 9.44,
    textAlign: 'right',
  },
  eventButtonDate: {
    fontFamily: fontFamily.regular,
    fontWeight: '400',
    fontSize: 8,
    lineHeight: 9.44,
  },
  eventButtonTime: {
    fontFamily: fontFamily.regular,
    fontWeight: '400',
    fontSize: 8,
    lineHeight: 9.44,
  },
  buttonItemContainer: {
    width: wp('100%'),
    alignItems: 'center',
  },
  buttonItem: {
    width: wp('85%'),
    padding: 10,
    backgroundColor: '#FFF',
    margin: 5,
    borderWidth: 0,
    height: hp('6.3%'),
    borderColor: colors.buttonPrimary,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    overflow: 'visible',
  },
  itemImageContainer: {
    width: wp('10.4%'),
    height: hp('5.5%'),
    marginLeft: wp('8%'),
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    paddingTop: 5,
    left: -40,
    backgroundColor: colors.white, // This is for Android (elevation property)
  },
  arrowImg: {
    backgroundColor: colors.white,
    position: 'absolute',
    width: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    height: 20,
    right: -12,
  },
  buttonItemHorizontal: {
    padding: 5,
    backgroundColor: colors.white,
    margin: 5,
    borderRadius: 10,
    width: wp('22%'),
  },
  eventButtonToday: {
    padding: 5,
    backgroundColor: colors.white,
    margin: 5,
    borderRadius: 10,
    borderWidth: 1,
    elevation: 1,
    borderRadius: 12,
    borderColor: colors.white,
  },
  eventButtonUpdateToday: {
    padding: 5,
    backgroundColor: colors.white,
    margin: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderRadius: 12,
    borderColor: colors.buttonPrimary,
  },
  backButtonText: {
    color: '#592B81',
    fontSize: 21,
    fontWeight: 'bold',
    marginHorizontal: 5,
  },
  mainHorizontalUpperContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 2,
    paddingHorizontal: 6,
  },
  spacerTopContainer: {
    width: wp('5%'),
  },
  titleTextEventContainer: {
    justifyContent: 'center',
  },
  at_vsContainer: {
    backgroundColor: '#592C82',
    borderRadius: 100,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleAt_VsTextEvent: {
    fontSize: fontSize.vvSmall,
    fontFamily: fontFamily.regular,
    fontWeight: '500',
    color: colors.white,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  imageRenderItemStyle: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 30,
    padding: 2,
  },
  titleContainerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 5,
  },
  containerImageStyle: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerButtonLink: {
    flexDirection: 'row',
    justifyContent: 'center',
    margin: 0,
    padding: 0,
  },
});
