import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

import {colors, fontFamily, fontSize} from '../../comman';

export const styles = StyleSheet.create({
  topImageContainer: {
    alignItems: 'center',
    marginTop: hp('1%'),
    marginBottom: hp('-2%'),
  },
  mainContainer: {
    marginTop: 21,
  },
  headingTextToday: {
    fontSize: fontSize.small,
    fontFamily: fontFamily.black,
    fontWeight: '600',
    textAlign: 'center',
    color: colors.buttonPrimary,
  },
  headingTextToday2: {
    fontSize: fontSize.small,
    fontFamily: fontFamily.black,
    fontWeight: '600',
    textAlign: 'center',
    color: colors.black,
  },
  mainTodayConainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
  },
  topImageEventContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  image: {
    height: 120,
    width: 120,
  },
  imageIcon1: {
    height: 54,
    width: 74,
  },
  imagesContainerHorizontal: {
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mainTextContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  UnaTextView: {
    flex: 1,
    alignItems: 'center',
  },
  teamsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: wp('1.5%'),
    paddingVertical: hp('1%'),
  },
  secondContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp('2%'),
  },
  thirdContainer: {
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  headingText: {
    fontSize: hp(2.4),
    fontFamily: fontFamily.bold,
    fontWeight: '600',
    paddingHorizontal: 15,
    paddingTop: 30,
  },
  headingText2: {
    fontSize: fontSize.small,
    fontFamily: fontFamily.regular,
    fontWeight: '600',
  },
  headingText3: {
    fontSize: fontSize.xxxtinyH,
    fontFamily: fontFamily.black,
    fontWeight: '600',
    lineHeight: 14.4,
    textAlign: 'center',
    color: colors.greyishColor,
  },
  titleTextEvent: {
    fontSize: fontSize.tiny,
    fontFamily: fontFamily.regular,
    fontWeight: '600',
    color: colors.black,
    textAlign: 'center',
    width: 77,
  },
  opponentTitleTextEvent: {
    fontSize: fontSize.tiny,
    fontFamily: fontFamily.regular,
    fontWeight: '600',
    color: colors.black,
    textAlign: 'center',
    flexWrap: 'wrap',
    width: wp('30%'),
  },
  opponentTitleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  bottomTitleTextEvent: {
    fontSize: fontSize.tiny,
    fontFamily: fontFamily.regular,
    fontWeight: '600',
    color: colors.black,
    textAlign: 'center',
  },
  bottomTournamentTitleTextEvent: {
    fontSize: fontSize.xxtiny,
    fontFamily: fontFamily.regular,
    fontWeight: '400',
    color: '#592C82',
    textAlign: 'center',
  },
  titleAt_VsTextEvent: {
    fontSize: fontSize.xsmall,
    fontFamily: fontFamily.regular,
    fontWeight: '500',
    color: colors.white,
    textAlign: 'center',
    textTransform: 'uppercase',
    width: 77,
  },
  titleTextEventContainer: {
    justifyContent: 'center',
    marginLeft: 37,
    marginRight: 40,
  },
  at_vsContainer: {
    backgroundColor: '#592C82',
    borderRadius: 100,
    width: 38,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleTextEvent2: {
    fontSize: fontSize.xxtiny,
    fontFamily: fontFamily.regular,
    fontWeight: '400',
    color: colors.greyishColor,
  },
  mainEventTextContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: hp('1%'),
  },
  secondaryEventTextContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 110,
    marginVertical: hp('1%'),
  },
  headingTextHeader: {
    fontSize: fontSize.normal,
    fontFamily: fontFamily.regular,
    fontWeight: '700',
    textAlign: 'center',
    color: colors.buttonPrimary,
  },
  topHeadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp('2.5%'),
    flexDirection: 'row',
    marginHorizontal: wp('5%'),
    justifyContent: 'space-between',
    marginHorizontal: 20,
  },
  topContainerText: {
    fontFamily: fontFamily.regular,
    fontWeight: '400',
    fontSize: 8,
    lineHeight: 9.44,
    textAlign: 'right',
  },
  buttonItem: {
    width: wp('90%'),
    backgroundColor: colors.white,
    margin: 5,
    elevation: 3,
    shadowColor: colors.balack,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 3,
    borderRadius: 12,
  },
  buttonItemPurple: {
    width: wp('90%'),
    backgroundColor: colors.white,
    margin: 5,
    elevation: 3,
    shadowColor: colors.balack,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.buttonPrimary,
  },
  imageEventStyle: {
    width: wp('40%'),
  },
  imageEventStyle2: {
    height: hp('20%'),
    width: wp('50%'),
  },
  buttonItemHorizontal: {
    padding: 10,
    backgroundColor: colors.white,
    margin: 5,
    borderRadius: 10,
  },
  mainHorizontalUpperContainer: {
    flexDirection: 'row',
  },
  spacerTopContainer: {
    width: wp('5%'),
  },
  fotterContainer: {
    backgroundColor: '#F2F2F2',
    borderRadius: 5,
    marginHorizontal: 11,
    marginTop: 13,
    marginBottom: 11,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 7,
  },
});
