import {
  BuyTicketsSvgComponent,
  VisitTeamShopSvgComponent,
  ListenIconSvgComponent,
  WatchIconSvgComponent,
  BookSvgComponent,
  DonateSvgComponent,
} from '../utils';
import {images} from './image';

export const MainHomeData = [
  {
    id: 1,
    image: images.ticketImageImg,
    title: 'Buy Tickets',
    link: 'https://ds1.glitnirticketing.com/dsticket/web/ev_list.php',
  },
  {
    id: 2,
    image: images.homeImageImg,
    title: 'Visit Team Shop',
    link: 'https://www.amazon.com/stores/page/4ADCAA1D-25AD-4EFB-AE27-39FD3CD70D4D',
  },
  {
    id: 3,
    image: images.tvIconImageImg,
    title: 'Watch',
    link: 'https://www.espn.com/watch/catalog/302bca11-b142-41e5-a456-9d2edcbbaae8/asun#bucketId=29461&sourceCollection=Browse_by_Conference',
  },
  {
    id: 4,
    image: images.listenIconImageImg,
    title: 'Listen',
    link: 'https://streamdb7web.securenetsystems.net/cirrusencore/index.cfm?stationCallSign=WLLX',
  },
  {
    id: 5,
    image: images.gameProgramIconImageImg,
    title: 'Game Programs',
    link: 'PdfScreen',
  },
  {
    id: 6,
    image: images.donateIconImage,
    title: 'Donate',
    link: 'https://www.givecampus.com/campaigns/34646/donations/new?a=6266417',
  },
];
// export const MainHomeData = [
//   {
//     id: 1,
//     image: <BuyTicketsSvgComponent />,
//     title: 'Buy Tickets',
//     link: 'https://ds1.glitnirticketing.com/dsticket/web/ev_list.php',
//   },
//   {
//     id: 2,
//     image: <VisitTeamShopSvgComponent />,
//     title: 'Visit Team Shop',
//     link: 'https://www.amazon.com/stores/page/4ADCAA1D-25AD-4EFB-AE27-39FD3CD70D4D',
//   },
//   {
//     id: 3,
//     image: <WatchIconSvgComponent />,
//     title: 'Watch',
//     link: 'https://www.espn.com/watch/catalog/302bca11-b142-41e5-a456-9d2edcbbaae8/asun#bucketId=29461&sourceCollection=Browse_by_Conference',
//   },
//   {
//     id: 4,
//     image: <ListenIconSvgComponent />,
//     title: 'Listen',
//     link: 'https://streamdb7web.securenetsystems.net/cirrusencore/index.cfm?stationCallSign=WLLX',
//   },
//   {
//     id: 5,
//     image: <BookSvgComponent />,
//     title: 'Game Programs',
//     link: 'PdfScreen',
//   },
//   {
//     id: 6,
//     image: <DonateSvgComponent />,
//     title: 'Donate',
//     link: 'https://www.givecampus.com/campaigns/34646/donations/new?a=6266417',
//   },
// ];

// export const MainHomeData2 = [
//   {
//     id: 1,
//     image: <BuyTicketsSvgComponent />,
//     title: 'Buy Tickets',
//     link: 'https://ds1.glitnirticketing.com/dsticket/web/ev_list.php',
//   },
//   {
//     id: 2,
//     image: <VisitTeamShopSvgComponent />,
//     title: 'Visit Team Shop',
//     link: 'https://www.amazon.com/stores/page/4ADCAA1D-25AD-4EFB-AE27-39FD3CD70D4D',
//   },
//   {
//     id: 3,
//     image: <WatchIconSvgComponent />,
//     title: 'Watch',
//     link: 'https://www.espn.com/watch/catalog/302bca11-b142-41e5-a456-9d2edcbbaae8/asun#bucketId=29461&sourceCollection=Browse_by_Conference',
//   },
//   {
//     id: 4,
//     image: <ListenIconSvgComponent />,
//     title: 'Listen',
//     link: 'https://streamdb7web.securenetsystems.net/cirrusencore/index.cfm?stationCallSign=WLLX',
//   },
//   {
//     id: 5,
//     image: <DonateSvgComponent />,
//     title: 'Donate',
//     link: 'https://www.givecampus.com/campaigns/34646/donations/new?a=6266417',
//   },
// ];

export const MainHomeData2 = [
  {
    id: 1,
    image: images.ticketImageImg,
    title: 'Buy Tickets',
    link: 'https://ds1.glitnirticketing.com/dsticket/web/ev_list.php',
  },
  {
    id: 2,
    image: images.homeImageImg,
    title: 'Visit Team Shop',
    link: 'https://www.amazon.com/stores/page/4ADCAA1D-25AD-4EFB-AE27-39FD3CD70D4D',
  },
  {
    id: 3,
    image: images.teamICONImageImg,
    title: 'Watch',
    link: 'https://www.espn.com/watch/catalog/302bca11-b142-41e5-a456-9d2edcbbaae8/asun#bucketId=29461&sourceCollection=Browse_by_Conference',
  },
  {
    id: 4,
    image: images.listenIconImageImg,
    title: 'Listen',
    link: 'https://streamdb7web.securenetsystems.net/cirrusencore/index.cfm?stationCallSign=WLLX',
  },
  {
    id: 5,
    image: images.gameProgramIconImageImg,
    title: 'Donate',
    link: 'https://www.givecampus.com/campaigns/34646/donations/new?a=6266417',
  },
];

export const MainHomeDataRewards = [
  {
    id: 1,
    title: 'UNA Team T-Shirt',
    points: 5000,
  },
  {
    id: 2,
    title: 'UNA Team Hat',
    points: 2500,
  },
  {
    id: 3,
    title: '10% Off UNA Store',
    points: 1000,
  },
];
export const MainHomeDataHorizontal = [
  {
    id: 1,
    title: 'FootBall',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 2,
    title: 'FootBall',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 3,
    title: 'FootBall',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 4,
    title: 'FootBall',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 5,
    title: 'FootBall',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 6,
    title: 'FootBall',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 7,
    title: 'FootBall',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 8,
    title: 'FootBall',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
];

export const EventsData = [
  {
    id: 1,
    title: 'FootBall vs TSU',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 2,
    title: 'FootBall vs KSU',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 3,
    title: 'FootBall vs JSU',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 4,
    title: 'FootBall vs EKU',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 5,
    title: 'FootBall vs TSU',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 6,
    title: 'FootBall vs TSU',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 7,
    title: 'FootBall vs TSU',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
  {
    id: 8,
    title: 'FootBall vs TSU',
    score: '10/5',
    time: '6:00 PM CT',
    team1: 'UNA',
    team2: 'JSU',
  },
];

export const StoriesCardData = [
  {
    id: 1,
    title: 'North Alabama Athletics',
    reactangleIcon: images.rectangleIcon,
    heartRedIcon: images.heartRedIcon,
    messageIcon: images.messageIcon,
    sendIcon: images.sendIcon,
    avatarIcon: images.avatarIcon,
    postImage: images.postImage,
  },
  {
    id: 2,
    title: 'North Alabama Athletics',
    reactangleIcon: images.rectangleIcon,
    heartRedIcon: images.heartRedIcon,
    messageIcon: images.messageIcon,
    sendIcon: images.sendIcon,
    avatarIcon: images.avatarIcon,
    postImage: images.gameDayImage,
  },
  {
    id: 3,
    title: 'North Alabama Athletics',
    reactangleIcon: images.rectangleIcon,
    heartRedIcon: images.heartRedIcon,
    messageIcon: images.messageIcon,
    sendIcon: images.sendIcon,
    avatarIcon: images.avatarIcon,
    postImage: images.postImage,
  },
  {
    id: 4,
    title: 'North Alabama Athletics',
    reactangleIcon: images.rectangleIcon,
    heartRedIcon: images.heartRedIcon,
    messageIcon: images.messageIcon,
    sendIcon: images.sendIcon,
    avatarIcon: images.avatarIcon,
    postImage: images.gameDayImage,
  },
  {
    id: 5,
    title: 'North Alabama Athletics',
    reactangleIcon: images.rectangleIcon,
    heartRedIcon: images.heartRedIcon,
    messageIcon: images.messageIcon,
    sendIcon: images.sendIcon,
    avatarIcon: images.avatarIcon,
    postImage: images.postImage,
  },
  {
    id: 6,
    title: 'North Alabama Athletics',
    reactangleIcon: images.rectangleIcon,
    heartRedIcon: images.heartRedIcon,
    messageIcon: images.messageIcon,
    sendIcon: images.sendIcon,
    avatarIcon: images.avatarIcon,
    postImage: images.gameDayImage,
  },
];

export const PROFESSIONOBJ = [
  {
    id: '1',
    name: 'Student',
  },
  {
    id: '2',
    name: 'Alumni',
  },
  {
    id: '3',
    name: 'Faculty',
  },
  {
    id: '4',
    name: 'Fan',
  },
];

export const FEEDBACKOBJ = [
  {
    id: '1',
    name: 'Gameday Issue',
  },
  {
    id: '2',
    name: 'App Issue',
  },
  {
    id: '3',
    name: 'Other Issue',
  },
];

export const PDF_LIST = [
  {
    id: 1,
    title: 'vs Chattanooga',
    date: '9/2/2023',
    image: 'https://roarlions.com/images/logos/UTC_2022.png',
    url: 'https://www.africau.edu/images/default/sample.pdf',
  },
];
export const NEWS_ROSTER = [
  {
    id: 1,
    posted: '8/20/2023',
    headLine: 'Sunday Staff Spotlight: Kerryon Johnson',
    category: 'Football',
  },
  {
    id: 2,
    posted: '8/24/2023',
    headLine: '2023 UNA Fall Sports Media Day Recap',
    category: `Football, General, Men's Cross Country, Women's Cross Country, Women's Soccer, Women's Volleyball`,
  },
  {
    id: 3,
    posted: '8/12/2023',
    headLine: 'UNA Football Notebook: Defensive Line Spotlight and Scrimmage',
    category: 'Football',
  },
  {
    id: 4,
    posted: '8/2/2023',
    headLine:
      '306 Barbecue to host weekly UNA Football Hour with Coach Brent Dearmon',
    category: 'Football',
  },
  {
    id: 5,
    posted: '8/13/2023',
    headLine: 'Archie Manning to headline annual Lion Pride Dinner and Auction',
    category: `Baseball, Football, General, Men's Basketball, Men's Cross Country, Men's Golf, Men's Tennis, Softball, Women's Basketball, Women's Cross Country, Women's Soccer, Women's Tennis, Women's Volleyball, Beach Volleyball, Women's Golf`,
  },
  {
    id: 6,
    posted: '8/17/2023',
    headLine:
      'Lion’s Share NIL Entity launches in support of North Alabama Athletics',
    category: `Baseball, Football, General, Men's Basketball, Men's Cross Country, Men's Golf, Men's Tennis, Softball, Women's Basketball, Women's Cross Country, Women's Soccer, Women's Tennis, Women's Track and Field, Women's Volleyball, Beach Volleyball, Women's Golf`,
  },
  {
    id: 7,
    posted: '8/27/2023',
    headLine: 'UNA Football Notebook: Defensive Back Spotlight',
    category: 'Football',
  },
];

export const Teams = [
  {
    id: '1',
    name: 'Football',
  },
  {
    id: '2',
    name: "Men's Basketball",
  },
  {
    id: '3',
    name: "Women's Basketball",
  },
  {
    id: '4',
    name: 'Baseball',
  },
  {
    id: '5',
    name: 'Softball',
  },
  {
    id: '6',
    name: "Men's Cross Country",
  },
  {
    id: '7',
    name: "Women's Cross Country",
  },
  {
    id: '8',
    name: "Men's Golf",
  },
  {
    id: '9',
    name: "Women's Golf",
  },
  {
    id: '10',
    name: "Men's Tennis",
  },
  {
    id: '11',
    name: "Women's Tennis",
  },
  {
    id: '12',
    name: "Women's Beach Volleyball",
  },
  {
    id: '13',
    name: "Women's Soccer",
  },
  {
    id: '14',
    name: "Women's Volleyball",
  },
];

export const FootballRoster = [
  {
    id: '1',
    image: '',
    number: '0',
    name: "Kam'ron Green",
    position: 'DE',
    year: 'Sophomore',
    hometown: 'Bradenton, FL',
  },
  {
    id: '2',
    image: '',
    number: '0',
    name: 'Jalen Hercules',
    position: 'TE',
    year: 'Junior',
    hometown: 'Oakland, CA',
  },
  {
    id: '3',
    image: '',
    number: '1',
    name: 'Demarcus Lacey',
    position: 'WR',
    year: 'Sophomore',
    hometown: 'Birmingham, AL',
  },
  {
    id: '4',
    image: '',
    number: '2',
    name: ' Allen Smith',
    position: 'DB',
    year: 'RS Junior',
    hometown: 'Culver City, CA',
  },
  {
    id: '5',
    image: '',
    number: '3',
    name: 'K.J. Trujillo',
    position: 'DB',
    year: 'RS Junior',
    hometown: 'Los Angeles, CA',
  },
  {
    id: '6',
    image: '',
    number: '4',
    name: ' Parker Driggers',
    position: 'RB',
    year: 'RS Junior',
    hometown: 'Brantley, AL',
  },
  {
    id: '7',
    image: '',
    number: '5',
    name: 'Justin Douglas',
    position: 'DB',
    year: 'Senior',
    hometown: 'Atlanta, GA',
  },
  {
    id: '8',
    image: '',
    number: '5',
    name: 'Takairee Kenebrew',
    position: 'WR',
    year: 'RS Senior',
    hometown: 'Childersburg, AL',
  },
  {
    id: '9',
    image: '',
    number: '6',
    name: 'Gallil Guillaume',
    position: 'LB',
    year: 'Senior',
    hometown: 'Suwanee, GA',
  },
  {
    id: '10',
    image: '',
    number: '6',
    name: 'Noah Walters',
    position: 'QB',
    year: 'Sophomore',
    hometown: 'Lincoln, NE',
  },
  {
    id: '11',
    image: '',
    number: '7',
    name: 'Ben Harris',
    position: 'DE',
    year: 'RS Sophomore',
    hometown: 'Midwest City, OK',
  },
  {
    id: '12',
    image: '',
    number: '8',
    name: 'Cameron Jamar',
    position: 'DB',
    year: 'RS Sophomore',
    hometown: 'New Market, AL',
  },
  {
    id: '13',
    image: '',
    number: '9',
    name: 'E.J. Rogers',
    position: 'WR',
    year: 'RS Junior',
    hometown: 'Wetumpka, AL',
  },
  {
    id: '14',
    image: '',
    number: '12',
    name: 'Jaquan Woods',
    position: 'WR',
    year: 'RS Sophomore',
    hometown: 'Gadsden, AL',
  },
  {
    id: '15',
    image: '',
    number: '13',
    name: 'Barry Womack',
    position: 'DB',
    year: 'Senior',
    hometown: 'Montgomery, AL',
  },
  {
    id: '16',
    image: '',
    number: '14',
    name: 'Kobe Warden',
    position: 'WR',
    year: 'RS Junior',
    hometown: 'Killen, AL',
  },
  {
    id: '17',
    image: '',
    number: '15',
    name: 'Jacob Peters',
    position: 'CB',
    year: 'Junior',
    hometown: 'Muscle Shoals, AL',
  },
  {
    id: '18',
    image: '',
    number: '16',
    name: 'Javen Augustus',
    position: 'DL',
    year: 'Sophomore',
    hometown: 'Montgomery, AL',
  },
  {
    id: '19',
    image: '',
    number: '17',
    name: 'Christian Jones',
    position: 'LB',
    year: 'Junior',
    hometown: 'Roanoke, AL',
  },
  {
    id: '20',
    image: '',
    number: '18',
    name: 'Justin Luke',
    position: 'WR',
    year: 'RS Sophomore',
    hometown: 'Warner Robins, GA',
  },
  {
    id: '21',
    image: '',
    number: '19',
    name: 'Dakota Warfield',
    position: 'WR',
    year: 'Senior',
    hometown: 'Alpharetta, GA',
  },
  {
    id: '22',
    image: '',
    number: '21',
    name: 'Ashaad Williams',
    position: 'LB',
    year: 'RS Sophomore',
    hometown: 'Russellville, AL',
  },
  {
    id: '23',
    image: '',
    number: '23',
    name: 'Micah Finn',
    position: 'DL',
    year: 'Junior',
    hometown: 'Dickson, TN',
  },
  {
    id: '24',
    image: '',
    number: '25',
    name: 'Keenan Hill',
    position: 'DB',
    year: 'RS Freshman',
    hometown: 'Detroit, MI',
  },
  {
    id: '25',
    image: '',
    number: '26',
    name: 'Riely Evans',
    position: 'TE',
    year: 'RS Junior',
    hometown: 'Courtland, AL',
  },
  {
    id: '26',
    image: '',
    number: '28',
    name: 'Shaun Myers',
    position: 'LB',
    year: 'Junior',
    hometown: 'Dayton, OH',
  },
  {
    id: '27',
    image: '',
    number: '29',
    name: 'Jamarion Augustus',
    position: 'LB',
    year: 'Sophomore',
    hometown: 'Montgomery, AL',
  },
  {
    id: '28',
    image: '',
    number: '31',
    name: 'Ryan Madison',
    position: 'DB',
    year: 'Sophomore',
    hometown: 'Fultondale, AL',
  },
  {
    id: '29',
    image: '',
    number: '32',
    name: 'Maleek Pope',
    position: 'RB',
    year: 'RS Freshman',
    hometown: 'Sylacauga, AL',
  },
  {
    id: '30',
    image: '',
    number: '33',
    name: 'E.J. Colbert',
    position: 'DL',
    year: 'RS Sophomore',
    hometown: 'Cordova, AL',
  },
  {
    id: '31',
    image: '',
    number: '34',
    name: 'Jalyn Daniels',
    position: 'RB',
    year: 'Sophomore',
    hometown: 'Tallassee, AL',
  },
  {
    id: '32',
    image: '',
    number: '35',
    name: 'A.J. Phillips',
    position: 'LB',
    year: 'Junior',
    hometown: 'Mobile, AL',
  },
  {
    id: '33',
    image: '',
    number: '36',
    name: 'Jakob Cummings',
    position: 'LB',
    year: 'RS Senior',
    hometown: 'Auburn, AL',
  },
  {
    id: '34',
    image: '',
    number: '37',
    name: 'Sam Contorno',
    position: 'K',
    year: 'RS Junior',
    hometown: 'Tuscaloosa, AL',
  },
  {
    id: '35',
    image: '',
    number: '38',
    name: 'Garrick Ponder',
    position: 'LB',
    year: 'RS Freshman',
    hometown: 'Largo, FL',
  },
  {
    id: '36',
    image: '',
    number: '39',
    name: 'Damion Fitzpatrick',
    position: 'DB',
    year: 'RS Sophomore',
    hometown: 'Lithonia, GA',
  },
  {
    id: '37',
    image: '',
    number: '40',
    name: 'Scott Robinson',
    position: 'K',
    year: 'RS Sophomore',
    hometown: 'Iuka, MS',
  },
  {
    id: '38',
    image: '',
    number: '41',
    name: 'Tyler Antkowiak',
    position: 'DE',
    year: 'RS Junior',
    hometown: 'Trussville, AL',
  },
  {
    id: '39',
    image: '',
    number: '42',
    name: 'Thomas Dowis',
    position: 'K',
    year: 'RS Sophomore',
    hometown: 'Bogart, GA',
  },
  {
    id: '40',
    image: '',
    number: '43',
    name: 'Keldan Moore',
    position: 'DL',
    year: 'RS Sophomore',
    hometown: 'Gallatin, TN',
  },
  {
    id: '51',
    image: '',
    number: '45',
    name: 'Tyrik Daniels',
    position: 'DL',
    year: 'RS Sophomore',
    hometown: 'Demopolis, AL',
  },
  {
    id: '52',
    image: '',
    number: '46',
    name: 'Myles Murphy',
    position: 'RB',
    year: 'RS Freshman',
    hometown: 'Pensacola, FL',
  },
  {
    id: '53',
    image: '',
    number: '47',
    name: 'Cole Cavin',
    position: 'TE',
    year: 'RS Freshman',
    hometown: 'Trian, GA',
  },
  {
    id: '54',
    image: '',
    number: '48',
    name: 'Philip Ossai',
    position: 'DL',
    year: 'Senior',
    hometown: 'Conroe, TX',
  },
  {
    id: '55',
    image: '',
    number: '50',
    name: 'Amir Graham',
    position: 'OL',
    year: 'RS Freshman',
    hometown: 'Pensacola, FL',
  },
  {
    id: '56',
    image: '',
    number: '52',
    name: 'Drew Beddingfield',
    position: 'DL',
    year: 'RS Senior',
    hometown: 'Elkmont, AL',
  },
  {
    id: '57',
    image: '',
    number: '54',
    name: 'Carson Hill',
    position: 'OL',
    year: 'RS Freshman',
    hometown: 'Cullman, AL',
  },
  {
    id: '58',
    image: '',
    number: '56',
    name: 'Trenton Townsend',
    position: 'DL',
    year: 'Junior',
    hometown: 'Kennesaw, GA',
  },
  {
    id: '59',
    image: '',
    number: '63',
    name: 'Brody Gravitt',
    position: 'OL',
    year: 'RS Freshman',
    hometown: 'Haleyville, AL',
  },
  {
    id: '60',
    image: '',
    number: '64',
    name: 'Mack McCluskey',
    position: 'OL',
    year: 'Junior',
    hometown: 'Florence, AL',
  },
  {
    id: '61',
    image: '',
    number: '65',
    name: 'Stevie Young',
    position: 'OL',
    year: 'Senior',
    hometown: 'Ft. Smith, AR',
  },
  {
    id: '62',
    image: '',
    number: '67',
    name: 'Logan McInnish',
    position: 'OL',
    year: 'RS Sophomore',
    hometown: 'Muscle Shoals, AL',
  },
  {
    id: '63',
    image: '',
    number: '68',
    name: 'Collin Wright',
    position: 'OL',
    year: 'RS Freshman',
    hometown: 'Muscle Shoals, AL',
  },
  {
    id: '64',
    image: '',
    number: '70',
    name: 'Nathan Brown',
    position: 'OL',
    year: 'RS Junior',
    hometown: 'Spanish Fort, AL',
  },
  {
    id: '65',
    image: '',
    number: '71',
    name: 'Denzel Holder',
    position: 'OL',
    year: 'RS Freshman',
    hometown: 'Birmingham, AL',
  },
  {
    id: '66',
    image: '',
    number: '73',
    name: 'Edgerrin Watson',
    position: 'OL',
    year: 'RS Freshman',
    hometown: 'Huntsville, AL',
  },
  {
    id: '67',
    image: '',
    number: '74',
    name: 'Gage Saint',
    position: 'OL',
    year: 'Junior',
    hometown: 'Hatton, AL',
  },
  {
    id: '68',
    image: '',
    number: '75',
    name: 'Will Derico',
    position: 'OL',
    year: 'Senior',
    hometown: 'Montgomery, AL',
  },
  {
    id: '69',
    image: '',
    number: '76',
    name: "Fau Tai'Vai",
    position: 'OL',
    year: 'Junior',
    hometown: 'Melbourne, Australia',
  },
  {
    id: '70',
    image: '',
    number: '77',
    name: 'Mickel Clay',
    position: 'OL',
    year: 'Junior',
    hometown: 'Cincinnati, OH',
  },
  {
    id: '71',
    image: '',
    number: '79',
    name: 'Raykwon Goldthwaite',
    position: 'OL',
    year: 'RS Freshman',
    hometown: 'Birmingham, AL',
  },
  {
    id: '72',
    image: '',
    number: '80',
    name: 'Sawyer Heptinstall',
    position: 'WR',
    year: 'RS Sophomore',
    hometown: 'Blountsville, AL',
  },
  {
    id: '73',
    image: '',
    number: '81',
    name: 'Ollie Finch, Jr.',
    position: 'WR',
    year: 'RS Sophomore',
    hometown: 'Attalla, AL',
  },
  {
    id: '74',
    image: '',
    number: '82',
    name: 'Tylen Campbell',
    position: 'WR',
    year: 'RS Freshman',
    hometown: 'Jackson, AL',
  },
  {
    id: '75',
    image: '',
    number: '83',
    name: 'Nikki Taylor',
    position: 'WR',
    year: 'RS Freshman',
    hometown: 'Luverne, AL',
  },
  {
    id: '76',
    image: '',
    number: '85',
    name: 'Jakobie Hurley',
    position: 'WR',
    year: 'RS Freshman',
    hometown: 'Florence, AL',
  },
  {
    id: '77',
    image: '',
    number: '86',
    name: 'Phil McDuff',
    position: 'LB',
    year: 'RS Sophomore',
    hometown: 'Tuscaloosa, AL',
  },
  {
    id: '78',
    image: '',
    number: '88',
    name: 'Kaleb Heatherly',
    position: 'TE',
    year: 'Sophomore',
    hometown: 'Cullman, AL',
  },
  {
    id: '79',
    image: '',
    number: '89',
    name: 'Kenny Rawls',
    position: 'TE',
    year: 'RS Junior',
    hometown: 'Franklin, TN',
  },
  {
    id: '80',
    image: '',
    number: '91',
    name: 'Jake McCluskey',
    position: 'DT',
    year: 'RS Freshman',
    hometown: 'Florence, AL',
  },
  {
    id: '81',
    image: '',
    number: '94',
    name: 'Jake Ingram',
    position: 'DE',
    year: 'RS Freshman',
    hometown: 'Pelham, AL',
  },
  {
    id: '82',
    image: '',
    number: '95',
    name: 'Elijah Hartnett',
    position: 'TE',
    year: 'RS Freshman',
    hometown: 'Florence, AL',
  },
];

export const BaseballRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2023/1/14/Hudson_Drew2023Mug1_1N9Dd.jpg?width=300',
    number: '2',
    name: 'Drew Hudson',
    position: 'SS/2B',
    year: 'Senior',
    hometown: 'Arab, AL',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2023/1/14/Frei_Gehrig2023Mug1_2NWK4.jpg?width=300',
    number: '4',
    name: 'Gehrig Frei',
    position: 'SS',
    year: 'Senior',
    hometown: 'Alpharetta, GA',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2023/1/14/Machado_Kyle2023Mug1_LSWBk.jpg?width=300',
    number: '5',
    name: 'Kyle Machado',
    position: 'Infield',
    year: 'Graduate',
    hometown: 'Punta Gorda, FL',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2023/1/14/Howard_Carson2023Mug1_7hrfJ.jpg?width=300',
    number: '7',
    name: 'Carson Howard',
    position: 'RHP',
    year: 'Sophomore',
    hometown: 'Pike Road, AL',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2023/1/14/Lane_Jonathan2023Mug1_CpyUI.jpg?width=300',
    number: '8',
    name: 'Jonathan Lane',
    position: 'Outfield',
    year: 'Sophomore',
    hometown: 'Fort Lauderdale, FL',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2023/1/14/Ferrigno_Jackson2023Mug1_RmR8f.jpg?width=300',
    number: '9',
    name: 'Jackson Ferrigno',
    position: 'Infield',
    year: 'RS Freshman',
    hometown: 'Farmington, CT',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2023/1/14/James.Jacon2023Mug1_92aBB.jpg?width=300',
    number: '10',
    name: 'Jacob James',
    position: 'LHP',
    year: 'Junior',
    hometown: 'Loretto, TN',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2023/1/14/Petty_Quinn2023Mug1_Vy3tF.jpg?width=300',
    number: '11',
    name: 'Quinn Petty',
    position: '3B',
    year: 'Sophomore',
    hometown: 'Cumming, GA',
  },
  {
    id: '9',
    image:
      'https://www.roarlions.com/images/2023/1/14/Hudson_Will2023Mug1_M286L.jpg?width=300',
    number: '12',
    name: 'Will HUdson',
    position: 'RHP',
    year: 'RS Sophomore',
    hometown: 'Arab, AL',
  },
  {
    id: '10',
    image:
      'https://www.roarlions.com/images/2023/1/14/McIntyre_Dominick2023Mug1_WHi0y.jpg?width=300',
    number: '13',
    name: 'Dominich McIntyre',
    position: 'Outfield',
    year: 'Junior',
    hometown: 'Lawrenceville, GA',
  },
  {
    id: '11',
    image:
      'https://www.roarlions.com/images/2023/1/14/Knight_Andrew2023Mug1_PtwM4.jpg?width=300',
    number: '14',
    name: 'Andrew Knight',
    position: 'Catcher',
    year: 'Graduate',
    hometown: 'Vestavia Hills, AL',
  },
  {
    id: '12',
    image:
      'https://www.roarlions.com/images/2023/1/14/Bradshaw_Jacob2023Mug1_X63PK.jpg?width=300',
    number: '15',
    name: 'Jacob Bradshaw',
    position: 'RHP',
    year: 'Junior',
    hometown: 'Thomasville, GA',
  },
  {
    id: '13',
    image:
      'https://www.roarlions.com/images/2023/1/14/Walker_Ethan2023Mug1.jpg?width=300',
    number: '16',
    name: 'Ethan Walker',
    position: 'Outfield',
    year: 'Freshman',
    hometown: 'Kansas City, KS',
  },
  {
    id: '14',
    image:
      'https://www.roarlions.com/images/2023/1/14/Cook_Cal2023Mug1_Rxb8u.jpg?width=300',
    number: '17',
    name: 'Cal Cook',
    position: 'Outfield/1B',
    year: 'Senior',
    hometown: 'Knoxville, TN',
  },
  {
    id: '15',
    image:
      'https://www.roarlions.com/images/2023/1/14/Thomas_Peyton2023Mug1_VlI0w.jpg?width=300',
    number: '18',
    name: 'Peyton Thomas',
    position: 'Infield',
    year: 'Senior',
    hometown: 'Phil Campbell, AL',
  },
  {
    id: '16',
    image:
      'https://www.roarlions.com/images/2023/1/14/Jensen_Levi2023Mug1_oycPj.jpg?width=300',
    number: '19',
    name: 'Levi Jensen',
    position: 'Catcher',
    year: 'Junior',
    hometown: 'Luck, WI',
  },
  {
    id: '17',
    image:
      'https://www.roarlions.com/images/2023/1/14/Cheek_Jackson2023Mug1_HRNqr.jpg?width=300',
    number: '20',
    name: 'Jackson Cheek',
    position: 'Outfield',
    year: 'Freshman',
    hometown: 'Nettleton, MS',
  },
  {
    id: '18',
    image:
      'https://www.roarlions.com/images/2023/1/14/Agosto_Justus2023Mug1_PkPRe.jpg?width=300',
    number: '21',
    name: 'Justus Agosto',
    position: 'RHP',
    year: 'RS Freshman',
    hometown: 'Langhorne, PA',
  },
  {
    id: '19',
    image:
      'https://www.roarlions.com/images/2023/1/14/Parrish_Brycen2023Mug1_u1RmL.jpg?width=300',
    number: '22',
    name: 'Brycen Parrish',
    position: 'RHP',
    year: 'Junior',
    hometown: 'Florence, AL',
  },
  {
    id: '20',
    image:
      'https://www.roarlions.com/images/2023/1/14/Kingma_Evan2023Mug1_sfEby.jpg?width=300',
    number: '23',
    name: 'Evan Kingma',
    position: 'RHP',
    year: 'RS Junior',
    hometown: 'Bellingham, WA',
  },
  {
    id: '21',
    image:
      'https://www.roarlions.com/images/2023/1/14/Henrich_Kevin2023Mug1_qBRNE.jpg?width=300',
    number: '24',
    name: 'Kevin Henrich',
    position: 'RHP',
    year: 'Freshman',
    hometown: 'Malvern, PA',
  },
  {
    id: '22',
    image:
      'https://www.roarlions.com/images/2023/1/14/Morris_Will2023Mug1_NLaez.jpg?width=300',
    number: '25',
    name: 'Will Morris',
    position: 'RHP',
    year: 'Sophomore',
    hometown: 'Plainfield, IL',
  },
  {
    id: '23',
    image:
      'https://www.roarlions.com/images/2023/1/14/Shepherd.Will2023Mug1_8NZAh.jpg?width=300',
    number: '26',
    name: 'Will Shepherd',
    position: 'RHP',
    year: 'Freshman',
    hometown: 'Alpharetta, GA',
  },
  {
    id: '24',
    image:
      'https://www.roarlions.com/images/2023/1/14/Johnson_Andin2023Mug1_X7S3O.jpg?width=300',
    number: '28',
    name: 'Andin Johnson',
    position: 'Catcher',
    year: 'Junior',
    hometown: 'Amory, MS',
  },
  {
    id: '25',
    image:
      'https://www.roarlions.com/images/2023/1/14/Battle_Justin2023Mug1_FJxwV.jpg?width=300',
    number: '29',
    name: 'Justin Battle',
    position: 'RHP',
    year: 'Freshman',
    hometown: 'Murfreesboro, TN',
  },
  {
    id: '26',
    image:
      'https://www.roarlions.com/images/2023/1/14/Majer_Zak2023Mug1_93w4s.jpg?width=300',
    number: '30',
    name: 'Zak Majer',
    position: 'Outfield',
    year: 'RS Sophomore',
    hometown: 'Plantation, FL',
  },
  {
    id: '27',
    image:
      'https://www.roarlions.com/images/2023/1/14/Claunch_Raleigh2023Mug1_qrm0f.jpg?width=300',
    number: '31',
    name: 'Raleigh Claunch',
    position: 'RHP',
    year: 'RS Freshman',
    hometown: 'Florence, AL',
  },
  {
    id: '28',
    image:
      'https://www.roarlions.com/images/2023/1/14/Bowerman_Josh2023Mug1_Fx4Ko.jpg?width=300',
    number: '33',
    name: 'Josh Bowerman',
    position: 'RHP',
    year: 'Freshman',
    hometown: 'Florence, AL',
  },
  {
    id: '29',
    image:
      'https://www.roarlions.com/images/2023/1/14/Barnett_Caden2023Mug1_LfuJH.jpg?width=300',
    number: '34',
    name: 'Caden Barnett',
    position: 'RHP',
    year: 'Sophomore',
    hometown: 'Cullman, AL',
  },
  {
    id: '30',
    image:
      'https://www.roarlions.com/images/2023/1/14/Richter_Bryce2023Mug1_tPII3.jpg?width=300',
    number: '35',
    name: 'Bryce Richter',
    position: 'RHP',
    year: 'Junior',
    hometown: 'Excelsior, MN',
  },
  {
    id: '31',
    image:
      'https://www.roarlions.com/images/2023/1/14/Brown_Avery2023Mug1_lNtbp.jpg?width=300',
    number: '36',
    name: 'Avery Brown',
    position: 'RHP',
    year: 'Freshman',
    hometown: 'Sharpsburg, GA',
  },
  {
    id: '32',
    image:
      'https://www.roarlions.com/images/2023/1/14/Malecha_Joey2023Mug1_PPu4h.jpg?width=300',
    number: '37',
    name: 'Joey Malecha',
    position: 'RHP',
    year: 'Freshman',
    hometown: 'Northfield, MN',
  },
  {
    id: '33',
    image:
      'https://www.roarlions.com/images/2023/1/14/Lappe_Luke2023Mug1_xuShu.jpg?width=300',
    number: '38',
    name: 'Luke Lappe',
    position: '1B',
    year: 'RS Freshman',
    hometown: 'Meriden, CT',
  },
  {
    id: '34',
    image:
      'https://www.roarlions.com/images/2023/1/14/Cochran_Charlie2023Mug1_pmofe.jpg?width=300',
    number: '40',
    name: 'Charlie Cochran',
    position: 'Catcher',
    year: 'Freshman',
    hometown: 'Florence, AL',
  },
];

export const BasketballRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2022/10/23/WillSoucie2023.jpg?width=300',
    number: '0',
    name: 'Will Soucie',
    position: 'Guard',
    year: 'Sophomore',
    hometown: 'Califon, NJ',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2022/10/23/DetalianBrown2023.jpg?width=300',
    number: '1',
    name: 'Detalian Brown',
    position: 'Guard',
    year: 'Sophomore',
    hometown: 'Chicago, IL',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2022/10/23/DanielOrtiz2023.jpg?width=300',
    number: '2',
    name: 'Daniel Ortiz',
    position: 'Guard',
    year: 'Sophomore',
    hometown: 'Shreveport, LA',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2022/10/23/KJJohnson2023.jpg?width=300',
    number: '3',
    name: 'KJ Johnson',
    position: 'Guard',
    year: 'Junior',
    hometown: 'Lewisburg, TN',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2022/10/23/BrysonDawkins2023.jpg?width=300',
    number: '4',
    name: 'Bryson Dawkins',
    position: 'Forward',
    year: 'Freshman',
    hometown: 'Dothan, AL',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2022/10/23/JacariLane2023.jpg?width=300',
    number: '5',
    name: 'Jacari Lane',
    position: 'Guard',
    year: 'Freshman',
    hometown: 'Huntsville, AL',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2022/10/23/SawyerWright2023.jpg?width=300',
    number: '10',
    name: 'Sawyer Wright',
    position: 'Center',
    year: 'Sophomore',
    hometown: 'Tuscumbia, AL',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2022/10/23/AidanKuhl2023.jpg?width=300',
    number: '11',
    name: 'Aidan Kuhl',
    position: 'Guard',
    year: 'Freshman',
    hometown: 'Fort Collins, CO',
  },
  {
    id: '9',
    image:
      'https://www.roarlions.com/images/2022/10/23/BlakeFloyd2023.jpg?width=300',
    number: '13',
    name: 'Blake Floyd',
    position: 'Guard',
    year: 'Freshman',
    hometown: 'Pelham, AL',
  },
  {
    id: '10',
    image:
      'https://www.roarlions.com/images/2022/10/23/DetalianBrown2023.jpg?width=300',
    number: '21',
    name: 'Nikolas Gustavson',
    position: 'Forward',
    year: 'Sophomore',
    hometown: 'Helsinki, Finland',
  },
  {
    id: '11',
    image:
      'https://www.roarlions.com/images/2022/10/23/EoinNelson2023.jpg?width=300',
    number: '22',
    name: 'Eoin Nelson',
    position: 'Center',
    year: 'Junior',
    hometown: 'Dublin, Ireland',
  },
  {
    id: '12',
    image:
      'https://www.roarlions.com/images/2022/10/23/DerajeAgbaosi2023.jpg?width=300',
    number: '23',
    name: 'Deraje Agbaosi',
    position: 'Forward',
    year: 'Sophomore',
    hometown: 'Union, NJ',
  },
  {
    id: '13',
    image:
      'https://www.roarlions.com/images/2022/10/23/DamianForrest2023.jpg?width=300',
    number: '33',
    name: 'Damien Forrest',
    position: 'Forward',
    year: 'Junior',
    hometown: 'Fort Collins, CO',
  },
  {
    id: '14',
    image:
      'https://www.roarlions.com/images/2022/10/23/DallasHowell2023.jpg?width=300',
    number: '34',
    name: 'Dallas Howell',
    position: 'Forward',
    year: 'Sophomore',
    hometown: 'Coffee Springs, AL',
  },
];

export const CrossCountryRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2022/8/19/Allen_Evan2022Mug.jpg?width=300',
    number: null,
    name: 'Evan Allen',
    position: null,
    year: 'Junior',
    hometown: 'Henderson, TN',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2022/8/19/Bonsall_Noah2022Mug.jpg?width=300',
    number: null,
    name: 'Noah Bonsall',
    position: null,
    year: 'Sophomore',
    hometown: 'Scottsboro, AL',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2022/8/19/Hamlin_Jackson2022Mug.jpg?width=300',
    number: null,
    name: 'Jackson Hamlin',
    position: null,
    year: 'Freshman',
    hometown: 'Alabaster, AL',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2022/8/19/Hibbard_JJ2022Mug.jpg?width=300',
    number: null,
    name: 'James Hibbard',
    position: null,
    year: 'Senior',
    hometown: 'Colorado Springs, CO',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2022/8/19/Jackson_Connor2022Mug.jpg?width=300',
    number: null,
    name: 'Connor Jackson',
    position: null,
    year: 'Sophomore',
    hometown: 'Manila, AR',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2022/8/19/Jamieson_Edan2022Mug.jpg?width=300',
    number: null,
    name: 'Edan Jamieson',
    position: null,
    year: 'Sophomore',
    hometown: 'Helena, AL',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2022/8/19/Kiplagat_Kelvin2022Mug.jpg?width=300',
    number: null,
    name: 'Kelvin Kiplagat',
    position: null,
    year: 'Senior',
    hometown: "Moi's Bridge, Kenya",
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2022/8/19/Kipyego_Fedrick2022Mug.jpg?width=300',
    number: null,
    name: 'Fedrick Kipyego',
    position: null,
    year: 'Graduate',
    hometown: 'Eldoret, Kenya',
  },
  {
    id: '9',
    image:
      'https://www.roarlions.com/images/2022/8/19/Lee_Brandon2022Mug.jpg?width=300',
    number: null,
    name: 'Brandon Lee',
    position: null,
    year: 'Senior',
    hometown: 'Maylene, AL',
  },
  {
    id: '10',
    image:
      'https://www.roarlions.com/images/2022/8/19/Ludwig_Thomas2022Mug.jpg?width=300',
    number: null,
    name: 'Thomas Ludwig',
    position: null,
    year: 'Freshman',
    hometown: 'Chelsea, AL',
  },
  {
    id: '11',
    image:
      'https://www.roarlions.com/images/2022/8/19/Moore_Jake2022Mug.jpg?width=300',
    number: null,
    name: 'Jake Moore',
    position: null,
    year: 'Sophomore',
    hometown: 'Anniston, AL',
  },
  {
    id: '12',
    image:
      'https://www.roarlions.com/images/2022/8/19/Morris_Charles2022Mug.jpg?width=300',
    number: null,
    name: 'Charles Morris',
    position: null,
    year: 'Freshman',
    hometown: 'Hoover, AL',
  },
  {
    id: '13',
    image:
      'https://www.roarlions.com/images/2022/8/19/Nipper_Adam2022Mug.jpg?width=300',
    number: null,
    name: 'Adam Nipper',
    position: null,
    year: 'Sophomore',
    hometown: 'Plant City, FL',
  },
  {
    id: '14',
    image:
      'https://www.roarlions.com/images/2022/8/19/Pritchard_Talon2022Mug.jpg?width=300',
    number: null,
    name: 'Talon Pritchard',
    position: null,
    year: 'Junior',
    hometown: 'Helena, AL',
  },
  {
    id: '15',
    image:
      'https://www.roarlions.com/images/2022/8/19/Schrader_Mason2022Mug.jpg?width=300',
    number: null,
    name: 'Mason Schrader',
    position: null,
    year: 'Sophomore',
    hometown: 'Huntsville, AL',
  },
];

export const GolfRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2022/9/8/Abbott_Cory2022Mug2.jpg?width=300',
    number: null,
    name: 'Cory Abbott',
    position: null,
    year: 'Freshman',
    hometown: 'Houston, TX',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2022/9/8/Frizzell_Henry2022Mug2.jpg?width=300',
    number: null,
    name: 'Henry Frizzell',
    position: null,
    year: 'Junior',
    hometown: 'Frisco, TX',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2022/9/8/Garrett_Dawson2022Mug1.jpg?width=300',
    number: null,
    name: 'Dawson Garrett',
    position: null,
    year: 'Junior',
    hometown: 'Fort Payne, AL',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2022/9/8/Goodwin_Carter2022Mug1.jpg?width=300',
    number: null,
    name: 'Carter Goodwin',
    position: null,
    year: 'Senior',
    hometown: 'Hoover, AL',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2022/9/8/Jacobs_Andre2022Mug1.jpg?width=300',
    number: null,
    name: 'Andre Jacobs',
    position: null,
    year: 'Senior',
    hometown: 'League City, TX',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2022/9/8/Jacobs_Francois2022Mug2.jpg?width=300',
    number: null,
    name: 'Francois Jacobs',
    position: null,
    year: 'Senior',
    hometown: 'League City, TX',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2022/9/8/Luo_Xing2022Mug1.jpg?width=300',
    number: null,
    name: 'Xing "Eric" Luo',
    position: null,
    year: 'Freshman',
    hometown: 'Katy, TX',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2022/9/8/Nebout_Niko2022Mug1.jpg?width=300',
    number: null,
    name: 'Niko Nebout',
    position: null,
    year: 'Sophomore',
    hometown: 'League City, TX',
  },
];

export const TennisRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2023/1/16/Jamie_Bixby2023Mug1.jpg?width=300',
    number: null,
    name: 'Jamie Bixby',
    position: null,
    year: 'Junior',
    hometown: 'Brentwood, England',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2023/1/16/Lachlan_Brain2023Mug1.jpg?width=300',
    number: null,
    name: 'Lachlan Brain',
    position: null,
    year: 'Freshman',
    hometown: 'Adelaide, Australia',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2023/1/16/Guilherme_Diniz2023Mug1.jpg?width=300',
    number: null,
    name: 'Guilherme Diniz',
    position: null,
    year: 'Junior',
    hometown: 'Manaus, Brazil',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2023/1/16/Nazar_Fedoryshyn2023Mug1.jpg?width=300',
    number: null,
    name: 'Nazar Fedoryshyn',
    position: null,
    year: 'Sophomore',
    hometown: 'Lviv, Ukraine',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2023/1/16/Daniel_Leh2023Mug2.jpg?width=300',
    number: null,
    name: 'Daniel Leh',
    position: null,
    year: 'Junior',
    hometown: 'Kirbyville, TX',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2023/1/16/Carlos_Matarredona_Valor2023Mug1.jpg?width=300',
    number: null,
    name: 'Carlos Matarredona Valor',
    position: null,
    year: 'Senior',
    hometown: 'Alicante, Spain',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2023/1/16/Fedrricos_Scotuzzi2023Mug2.jpg?width=300',
    number: null,
    name: 'Fedrricos Scotuzzi',
    position: null,
    year: 'Freshman',
    hometown: 'Bergamo, Italy',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2023/1/16/Chris_Zhang2023Mug1.jpg?width=300',
    number: null,
    name: 'Chris Zhang',
    position: null,
    year: 'Sophomore',
    hometown: 'Aukland, New Zealand',
  },
];

export const WBasketballRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2022/10/23/CameronJones2023.jpg?width=300',
    number: '0',
    name: 'Cameron Jones',
    position: 'Guard',
    year: 'Freshman',
    hometown: 'Broadview Heights, Ohio',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2022/10/23/EmmaKateTittle2023.jpg?width=300',
    number: '1',
    name: 'Emma Kate Tittle',
    position: 'Guard',
    year: 'Freshman',
    hometown: 'Tuscumbia, AL',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2022/10/23/JadeMoore2023.jpg?width=300',
    number: '2',
    name: 'Jade Moore',
    position: 'Guard',
    year: 'Junior',
    hometown: 'St. Louis, MO',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2022/10/23/RuthBalogun2023.jpg?width=300',
    number: '3',
    name: 'Ruth Balogun',
    position: 'Forward',
    year: 'Sophomore',
    hometown: 'Lagos, Nigeria',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2022/10/23/SaraWohlgemuth2023.jpg?width=300',
    number: '5',
    name: 'Sara Wohlgemuth',
    position: 'Guard',
    year: 'Sophomore',
    hometown: 'Madison, CO',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2022/10/23/LexusGreen2023.jpg?width=300',
    number: '11',
    name: 'Lexus Green',
    position: 'Guard',
    year: 'Junior',
    hometown: 'Bakersfield, CA',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2022/10/23/AlexisCallins2023.jpg?width=300',
    number: '15',
    name: 'Alexis Callins',
    position: 'Guard',
    year: 'Junior',
    hometown: 'Martin, TN',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2022/10/23/OliviaJones2023.jpg?width=300',
    number: '20',
    name: 'Olivia Jones',
    position: 'Guard',
    year: 'Sophomore',
    hometown: 'Jackson, TN',
  },
  {
    id: '9',
    image:
      'https://www.roarlions.com/images/2022/10/23/RhemaPegues2023.jpg?width=300',
    number: '21',
    name: 'Rhema Pegues',
    position: 'Guard',
    year: 'Freshman',
    hometown: 'Olive Branch, MS',
  },
  {
    id: '10',
    image:
      'https://www.roarlions.com/images/2022/10/23/TyraFlowers2023_QaJ6s.jpg?width=300',
    number: '22',
    name: 'Tyra Flowers',
    position: 'Forward',
    year: 'Freshman',
    hometown: 'Winchester, KY',
  },
  {
    id: '11',
    image:
      'https://www.roarlions.com/images/2022/10/23/AlyssaClutter2023.jpg?width=300',
    number: '23',
    name: 'Alyssa Clutter',
    position: 'Guard',
    year: 'Freshman',
    hometown: 'Washington, PA',
  },
  {
    id: '12',
    image:
      'https://www.roarlions.com/images/2022/10/23/HinaSuzuki2023.jpg?width=300',
    number: '24',
    name: 'Hina Suzuki',
    position: 'Guard',
    year: 'Graduate',
    hometown: 'Hamamatsu, Japan',
  },
  {
    id: '13',
    image:
      'https://www.roarlions.com/images/2022/10/23/SkylerGill2023.jpg?width=300',
    number: '32',
    name: 'Skyler Gill',
    position: 'Guard/Forward',
    year: 'Sophomore',
    hometown: 'Wichita, KS',
  },
];

export const BeachVolleyballRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2023/1/25/Gerig_Katie2023Mug2.jpg?width=300',
    number: '1',
    name: 'Katie Gerig',
    position: null,
    year: 'Junior',
    hometown: 'Towanda, IL',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2023/1/25/Seney_Taylor2023Mug2.jpg?width=300',
    number: '2',
    name: 'Taylor Seney',
    position: null,
    year: 'Junior',
    hometown: 'Oak Creek, WI',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2023/1/25/Martin_Mackenzie2023Mug2.jpg?width=300',
    number: '5',
    name: 'Mackenzie Martin',
    position: null,
    year: 'Senior',
    hometown: 'Hoover, AL',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2023/1/25/Lewis_SarahLarkin2023Mug2.jpg?width=300',
    number: '10',
    name: 'Sarah Larkin Lewis',
    position: null,
    year: 'Freshman',
    hometown: 'Tyrone, GA',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2023/1/25/Klemperer_Paula2023Mug2.jpg?width=300',
    number: '11',
    name: 'Paula Klemperer',
    position: null,
    year: 'Senior',
    hometown: 'Hildesheim, Germany',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2023/1/25/Kordt_Natalie2023Mug2.jpg?width=300',
    number: '12',
    name: 'Natalie Kordt',
    position: null,
    year: 'Graduate',
    hometown: 'Bochum, Germany',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2023/1/25/Robertson_Abby2023Mug1.jpg?width=300',
    number: '13',
    name: 'Abby Robertson',
    position: null,
    year: 'Freshman',
    hometown: 'Franklin, TN',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2023/1/25/Andreson_Kati2023Mug3.jpg?width=300',
    number: '14',
    name: 'Kati Anderson',
    position: null,
    year: 'Freshman',
    hometown: 'Foley, AL',
  },
  {
    id: '9',
    image:
      'https://www.roarlions.com/images/2023/1/25/Robinson_Selma2023Mug1.jpg?width=300',
    number: '15',
    name: 'Selma Robinson',
    position: null,
    year: 'Freshman',
    hometown: 'Mölnlycke, Sweden',
  },
  {
    id: '10',
    image:
      'https://www.roarlions.com/images/2023/1/25/Conkle_Caroline2023Mug2.jpg?width=300',
    number: '21',
    name: 'Caroline Conkle',
    position: null,
    year: 'Junior',
    hometown: 'Arlington, TX',
  },
  {
    id: '11',
    image:
      'https://www.roarlions.com/images/2023/1/25/McLaurin_Martha2023Mug1.jpg?width=300',
    number: '22',
    name: 'Martha McLaurin',
    position: null,
    year: 'Junior',
    hometown: 'Gulf Shores, AL',
  },
  {
    id: '12',
    image:
      'https://www.roarlions.com/images/2023/1/25/Floyd_Katy2023Mug2.jpg?width=300',
    number: '23',
    name: 'Katy Floyd',
    position: null,
    year: 'Sophomore',
    hometown: 'Louisville, KY',
  },
  {
    id: '13',
    image:
      'https://www.roarlions.com/images/2023/1/25/Girod_Jelena2023Mug2.jpg?width=300',
    number: '24',
    name: 'Jelena Girod',
    position: null,
    year: 'Junior',
    hometown: 'Fort Wayne, IN',
  },
];

export const WCrossCountryRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2022/8/19/Anderson_Ashlyn2022Mug.jpg?width=300',
    number: null,
    name: 'Ashlyn Anderson',
    position: null,
    year: 'Sophomore',
    hometown: 'Mandeville, LA',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2022/8/19/Betts_Sage2022Mug.jpg?width=300',
    number: null,
    name: 'Sage Betts',
    position: null,
    year: 'Junior',
    hometown: "Lacey's Spring, AL",
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2022/8/19/Charo_Aaliyah2022Mug.jpg?width=300',
    number: null,
    name: 'Aaliyah Charo',
    position: null,
    year: 'Sophomore',
    hometown: 'Cotulla, TX',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2022/8/19/Daniel_Emily2022Mug.jpg?width=300',
    number: null,
    name: 'Emily Daniel',
    position: null,
    year: 'Junior',
    hometown: 'Moulton, AL',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2022/8/19/Grosso_Valerie2022Mug.jpg?width=300',
    number: null,
    name: 'Valerie Grosso',
    position: null,
    year: 'Junior',
    hometown: 'Lexington, AL',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2022/8/19/Humphries_Lillian2022Mug.jpg?width=300',
    number: null,
    name: 'Lillian Humphries',
    position: null,
    year: 'Senior',
    hometown: 'Cedar Park, TX',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2022/8/19/Jepkirui_Janeth2022Mug.jpg?width=300',
    number: null,
    name: 'Janeth Jepkirui',
    position: null,
    year: 'Sophomore',
    hometown: 'Eldoret, Kenya',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2022/8/19/Mathews_Graci22022Mug.jpg?width=300',
    number: null,
    name: 'Gracie Mathews',
    position: null,
    year: 'Sophomore',
    hometown: 'Springville, AL',
  },
  {
    id: '9',
    image:
      'https://www.roarlions.com/images/2022/8/19/McCarthy_Megan2022Mug.jpg?width=300',
    number: null,
    name: 'Meghan McCarthy',
    position: null,
    year: 'Sophomore',
    hometown: 'Rainbow City, AL',
  },
  {
    id: '10',
    image:
      'https://www.roarlions.com/images/2022/8/19/Mobley_Laura2022Mug.jpg?width=300',
    number: null,
    name: 'Laura Mobley',
    position: null,
    year: 'Sophomore',
    hometown: 'Lexington, TN',
  },
  {
    id: '11',
    image:
      'https://www.roarlions.com/images/2022/8/19/Pettus_Traci2022Mug.jpg?width=300',
    number: null,
    name: 'Traci Pettus',
    position: null,
    year: 'Freshman',
    hometown: 'Jasper, AL',
  },
  {
    id: '12',
    image:
      'https://www.roarlions.com/images/2022/8/19/Thomas_Mandaline2022Mug.jpg?width=300',
    number: null,
    name: 'Mandaline Thomas',
    position: null,
    year: 'Senior',
    hometown: 'Daphne, AL',
  },
  {
    id: '13',
    image:
      'https://www.roarlions.com/images/2022/8/19/Nipper_Adam2022Mug.jpg?width=300',
    number: null,
    name: 'Adam Nipper',
    position: null,
    year: 'Sophomore',
    hometown: 'Plant City, FL',
  },
  {
    id: '14',
    image:
      'https://www.roarlions.com/images/2022/8/19/Tucker_BethAnn2022Mug.jpg?width=300',
    number: null,
    name: 'Beth Ann Tucker',
    position: null,
    year: 'Sophomore',
    hometown: 'Springville, AL',
  },
  {
    id: '15',
    image:
      'https://www.roarlions.com/images/2022/8/19/White_EmmaKate2022Mug.jpg?width=300',
    number: null,
    name: 'Emma Kate White',
    position: null,
    year: 'Sophomore',
    hometown: 'Saltillo, MS',
  },
];

export const WGolfRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2022/9/8/Arp_Blakely2023Mug.jpg?width=300',
    number: null,
    name: 'Blakely Arp',
    position: null,
    year: 'Senior',
    hometown: 'LaGrange, GA',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2022/9/8/Brock_AnnaGrace2023Mug.jpg?width=300',
    number: null,
    name: 'Anna Grace Brock',
    position: null,
    year: 'Sophomore',
    hometown: 'Greenwood, SC',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2022/9/8/Dees_Hannah2023Mug.jpg?width=300',
    number: null,
    name: 'Hannah Dees',
    position: null,
    year: 'Sophomore',
    hometown: 'Fairhope, AL',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2022/9/8/Baral_Rose2023Mug.jpg?width=300',
    number: null,
    name: 'Zarah Fisher',
    position: null,
    year: 'Freshman',
    hometown: 'Durango, Mexico',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2022/9/8/Fisher_Zarah2023Mug.jpg?width=300',
    number: null,
    name: 'Allycia Gan',
    position: null,
    year: 'Junior',
    hometown: 'Selangar, Malaysia',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2022/9/8/Hays_AnnaMargaret2023Mug.jpg?width=300',
    number: null,
    name: 'Anna Margaret Hays',
    position: null,
    year: 'Junior',
    hometown: 'Muscle Shoals, AL',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2022/9/8/Klauber_Kerrigan2023Mug.jpg?width=300',
    number: null,
    name: 'Kerigan Klauber',
    position: null,
    year: 'Freshman',
    hometown: 'Athens, TN',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2022/9/8/Klemm_Jackie2023Mug.jpg?width=300',
    number: null,
    name: 'Jackie Klemm',
    position: null,
    year: 'Senior',
    hometown: 'Kelkheim, Germany',
  },
  {
    id: '9',
    image:
      'https://www.roarlions.com/images/2022/9/8/Pope_Hannah2023Mug.jpg?width=300',
    number: null,
    name: 'Hannah Pope',
    position: null,
    year: 'Senior',
    hometown: 'Florence, AL',
  },
  {
    id: '10',
    image:
      'https://www.roarlions.com/images/2022/9/8/Prakhya_Jahnavi2023Mug.jpg?width=300',
    number: null,
    name: 'Jahnavi Prakhya',
    position: null,
    year: 'Sophomore',
    hometown: 'Gujarat, India',
  },
  {
    id: '11',
    image:
      'https://www.roarlions.com/images/2022/9/8/Roush_Tori2023Mug.jpg?width=300',
    number: null,
    name: 'Tori Roush',
    position: null,
    year: 'Junior',
    hometown: 'Fairhope, AL',
  },
];

export const WTennisRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2023/1/16/Going_Kalais2023Mug1_JbYss.jpg?width=300',
    number: null,
    name: 'Kalais Going',
    position: null,
    year: 'Junior',
    hometown: 'Tauranga, New Zealand',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2023/1/16/Ana_Josic2023Mug6_2Pxc5.jpg?width=300',
    number: null,
    name: 'Ana Josic',
    position: null,
    year: 'Freshman',
    hometown: 'Subotica, Serbia',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2023/1/16/Anna_Marija_Bukina2023Mug1_eoSCy.jpg?width=300',
    number: null,
    name: 'Anna Marija Bukina',
    position: null,
    year: 'Graduate',
    hometown: 'Riga, Latvia',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2023/1/16/Martina_Paladini-Jennings2023Mug4_0Pw7j.jpg?width=300',
    number: null,
    name: 'Martina Paladini-Jennings',
    position: null,
    year: 'Graduate',
    hometown: 'London, England',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2023/1/16/Nicole_Reilly2023Mug2_ywtJy.jpg?width=300',
    number: null,
    name: 'Nicole Reilly',
    position: null,
    year: 'Junior',
    hometown: 'Huntsville, AL',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2023/1/16/Valeria_San_Miguel2023Mug2_PSFDX.jpg?width=300',
    number: null,
    name: 'Valeria San Miguel',
    position: null,
    year: 'Freshman',
    hometown: 'Cochabamba, Bolivia',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2023/1/16/Juliette_Talieu2023Mug1_taEet.jpg?width=300',
    number: null,
    name: 'Juliette Talieu',
    position: null,
    year: 'Junior',
    hometown: 'Paris, France',
  },
];

export const VolleyballRoster = [
  {
    id: '1',
    image: null,
    number: '3',
    name: 'Tatum Fouche',
    position: 'DS/LIB',
    year: 'Junior',
    hometown: 'Frisco, TX',
  },
  {
    id: '2',
    image: null,
    number: '4',
    name: 'Katie Gerig',
    position: 'DS/LIB',
    year: 'Senior',
    hometown: 'Towanda, IL',
  },
  {
    id: '3',
    image: null,
    number: '6',
    name: 'Anna Katherine Griggs',
    position: 'MB/OPP',
    year: 'Graduate',
    hometown: 'Arab, AL',
  },
  {
    id: '4',
    image: null,
    number: '7',
    name: 'Elif Ozsoy',
    position: 'S',
    year: 'Junior',
    hometown: 'Ankara, Turkey',
  },
  {
    id: '5',
    image: null,
    number: '9',
    name: 'Lucy Wedding',
    position: 'OH',
    year: 'Sophomore',
    hometown: 'Lexington, KY',
  },
  {
    id: '6',
    image: null,
    number: '12',
    name: 'Katy Floyd',
    position: 'OH',
    year: 'Junior',
    hometown: 'Louisville, KY',
  },
  {
    id: '7',
    image: null,
    number: '13',
    name: 'Kennedey Johnson',
    position: 'S',
    year: 'Senior',
    hometown: 'Castle Rock, CO',
  },
  {
    id: '8',
    image: null,
    number: '19',
    name: 'Mary Kate Stasevich',
    position: 'MB',
    year: 'Junior',
    hometown: 'Chesapeake, VA',
  },
  {
    id: '9',
    image: null,
    number: '21',
    name: 'Hayley Martin',
    position: 'OH',
    year: 'Sophomore',
    hometown: 'Elgin, IL',
  },
  {
    id: '10',
    image: null,
    number: '24',
    name: 'Mattrice Harris',
    position: 'MB',
    year: 'Graduate',
    hometown: 'Opelika, AL',
  },
  {
    id: '11',
    image: null,
    number: '25',
    name: 'Maggie Sullican',
    position: 'MB',
    year: 'Graduate',
    hometown: 'Tuscaloosa, AL',
  },
];

export const WSoccerRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2022/8/12/Yates_Payton2022Mug.jpg?width=300',
    number: '0',
    name: 'Payton Yates',
    position: 'Goalkeeper',
    year: 'Junior',
    hometown: 'Melbourne, FL',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2022/8/12/Spreck_Jordyn2022Mug.jpg?width=300',
    number: '1',
    name: 'Jordyn Spreck',
    position: 'Goalkeeper',
    year: 'Senior',
    hometown: 'St. Louis, MO',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2022/8/12/Andersson_Malin2022Mug.jpg?width=300',
    number: '2',
    name: 'Malin Andersson',
    position: 'Defender',
    year: 'Junior',
    hometown: 'Halmstad, Sweden',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2022/8/12/Fell_Chloe2022Mug.jpg?width=300',
    number: '3',
    name: 'Chloe Fell',
    position: 'Defender',
    year: 'Senior',
    hometown: 'Bury, England',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2022/8/12/Guthrie_Hannah2022Mug.jpg?width=300',
    number: '4',
    name: 'Hannah Guthrie',
    position: 'Defender',
    year: 'Senior',
    hometown: 'Gulf Shores, AL',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2022/8/12/Gurney_Izzi2022Mug.jpg?width=300',
    number: '5',
    name: 'Izzi Gurney',
    position: 'Defender',
    year: 'Senior',
    hometown: 'Corona, CA',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2022/8/12/Merkle_Montana2022Mug.jpg?width=300',
    number: '6',
    name: 'Montana Merkle',
    position: 'Defender',
    year: 'Sophomore',
    hometown: 'Cary, NC',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2022/8/12/Bussey_Alice2022Mug.jpg?width=300',
    number: '7',
    name: 'Alice Bussey',
    position: 'Forward',
    year: 'Junior',
    hometown: 'Hythe, England',
  },
  {
    id: '9',
    image:
      'https://www.roarlions.com/images/2022/8/12/Wiseman_Kate2022Mug.jpg?width=300',
    number: '8',
    name: 'Kate Wiseman',
    position: 'Midfielder',
    year: 'Graduate',
    hometown: 'Andover, England',
  },
  {
    id: '10',
    image:
      'https://www.roarlions.com/images/2022/8/12/Kellett_Charlotte2022Mug.jpg?width=300',
    number: '9',
    name: 'Charlotte Kellett',
    position: 'Forward',
    year: 'Graduate',
    hometown: 'Ipswich, England',
  },
  {
    id: '11',
    image:
      'https://www.roarlions.com/images/2022/8/12/Anderson_Olivia2022Mug.jpg?width=300',
    number: '10',
    name: 'Olivia Anderson',
    position: 'Forward',
    year: 'Freshman',
    hometown: 'Naperville, IL',
  },
  {
    id: '12',
    image:
      'https://www.roarlions.com/images/2022/8/12/Ebert_Morgan2022Mug.jpg?width=300',
    number: '13',
    name: 'Morgan Ebert',
    position: 'Defender',
    year: 'Graduate',
    hometown: 'Weldon Spring, MO',
  },
  {
    id: '13',
    image:
      'https://www.roarlions.com/images/2022/8/12/Duca_Lexi2022Mug.jpg?width=300',
    number: '14',
    name: 'Lexie Duca',
    position: 'Midfielder',
    year: 'Senior',
    hometown: 'Chelsea, AL',
  },
  {
    id: '14',
    image:
      'https://www.roarlions.com/images/2022/8/12/Parham_Molly2022Mug.jpg?width=300',
    number: '15',
    name: 'Molly Parham',
    position: 'Forward',
    year: 'Freshman',
    hometown: 'Tupelo, MS',
  },
  {
    id: '15',
    image:
      'https://www.roarlions.com/images/2022/8/12/Hass_Kendall2022Mug.jpg?width=300',
    number: '16',
    name: 'Kendall Hass',
    position: 'Defender',
    year: 'Freshman',
    hometown: 'Denver, CO',
  },
  {
    id: '16',
    image:
      'https://www.roarlions.com/images/2022/8/12/Schuster_Kira2022Mug.jpg?width=300',
    number: '17',
    name: 'Kira Schuster',
    position: 'Midfielder',
    year: 'Senior',
    hometown: 'Krefeld, Germany',
  },
  {
    id: '17',
    image:
      'https://www.roarlions.com/images/2022/8/12/Laroche_Katherine2022Mug.jpg?width=300',
    number: '20',
    name: 'Katherine Laroche',
    position: 'Midfielder',
    year: 'Senior',
    hometown: 'Quebec, Canada',
  },
  {
    id: '18',
    image:
      'https://www.roarlions.com/images/2022/8/12/Wingbermuehle_Reese2022Mug.jpg?width=300',
    number: '21',
    name: 'Reese Wingbermuehle',
    position: 'Defender',
    year: 'Junior',
    hometown: 'Imnperial, MO',
  },
  {
    id: '19',
    image:
      'https://www.roarlions.com/images/2022/8/12/Lensing_Hope2022Mug.jpg?width=300',
    number: '22',
    name: 'Hope Lensing',
    position: 'Forward',
    year: 'Sophomore',
    hometown: 'Evansville, IN',
  },
  {
    id: '20',
    image:
      'https://www.roarlions.com/images/2022/8/12/Lensing_Grace2022Mug.jpg?width=300',
    number: '23',
    name: 'Grace Lensing',
    position: 'Midfielder',
    year: 'Graduate',
    hometown: 'Evansville, IN',
  },
  {
    id: '21',
    image:
      'https://www.roarlions.com/images/2022/8/12/Patterson_Abby2022Mug.jpg?width=300',
    number: '24',
    name: 'Abby Patterson',
    position: 'Forward',
    year: 'Sophomore',
    hometown: 'Huntsville, AL',
  },
  {
    id: '22',
    image:
      'https://www.roarlions.com/images/2022/8/12/Bierbauer_Sarah2022Mug.jpg?width=300',
    number: '25',
    name: 'Sarah Bierbauer',
    position: 'Forward',
    year: 'Freshman',
    hometown: 'Madison, AL',
  },
  {
    id: '23',
    image:
      'https://www.roarlions.com/images/2022/8/12/Ellis_Grace2022Mug.jpg?width=300',
    number: '26',
    name: 'Grace Ellis',
    position: 'Defender',
    year: 'Sophomore',
    hometown: 'Vestavia Hills, AL',
  },
  {
    id: '24',
    image:
      'https://www.roarlions.com/images/2022/8/12/Kelly_AnnaGrace2022Mug.jpg?width=300',
    number: '27',
    name: 'Anna Grace Kelly',
    position: 'Defender',
    year: 'Sophomore',
    hometown: 'Auburn, AL',
  },
  {
    id: '25',
    image:
      'https://www.roarlions.com/images/2022/8/12/Cox_Ria2022Mug.jpg?width=300',
    number: '28',
    name: 'Ria Cox',
    position: 'Midfielder',
    year: 'Freshman',
    hometown: 'Chattanooga, TN',
  },
  {
    id: '26',
    image:
      'https://www.roarlions.com/images/2022/8/12/Sarkowski_Aubrey2022Mug.jpg?width=300',
    number: '30',
    name: 'Aubrey Sarkowski',
    position: 'Goalkeeper',
    year: 'Freshman',
    hometown: 'Auburn, AL',
  },
  {
    id: '27',
    image:
      'https://www.roarlions.com/images/2022/8/12/Watts_Alana2022Mug.jpg?width=300',
    number: '31',
    name: 'Alana Watts',
    position: 'Forward',
    year: 'Sophomore',
    hometown: 'Marietta, GA',
  },
  {
    id: '28',
    image:
      'https://www.roarlions.com/images/2022/8/12/Badskey_Peyton2022Mug.jpg?width=300',
    number: '32',
    name: 'Peyton Badskey',
    position: 'Goalkeeper',
    year: 'Junior',
    hometown: 'Elkhart, IN',
  },
];

export const SoftballRoster = [
  {
    id: '1',
    image:
      'https://www.roarlions.com/images/2022/10/31/HannahPrice2023.jpg?width=300',
    number: '00',
    name: 'Hannah Price',
    position: 'Pitcher',
    year: 'Freshman',
    hometown: 'Greenhill, AL',
  },
  {
    id: '2',
    image:
      'https://www.roarlions.com/images/2022/10/31/FelicityFrame2023.jpg?width=300',
    number: '1',
    name: 'Felicity Frame',
    position: 'Outfielder',
    year: 'Junior',
    hometown: 'McCalla, AL',
  },
  {
    id: '3',
    image:
      'https://www.roarlions.com/images/2022/10/31/BrookeBurback2023.jpg?width=300',
    number: '2',
    name: 'Brooke Burback',
    position: 'Catcher/Utility',
    year: 'Junior',
    hometown: 'Birmingham, AL',
  },
  {
    id: '4',
    image:
      'https://www.roarlions.com/images/2022/10/31/JessieBaughan2023.jpg?width=300',
    number: '3',
    name: 'Jessie Baughan',
    position: 'Outfield',
    year: 'Sophomore',
    hometown: 'Sumiton, AL',
  },
  {
    id: '5',
    image:
      'https://www.roarlions.com/images/2022/10/31/HaileyJones2023.jpg?width=300',
    number: '4',
    name: 'Hailey Jones',
    position: 'Utility',
    year: 'Sophomore',
    hometown: 'Summertown, TN',
  },
  {
    id: '6',
    image:
      'https://www.roarlions.com/images/2022/10/31/McKenziePatterson2023.jpg?width=300',
    number: '7',
    name: 'McKenzie Patterson',
    position: 'Outfielder',
    year: 'Junior',
    hometown: 'Corinth, MS',
  },
  {
    id: '7',
    image:
      'https://www.roarlions.com/images/2022/10/31/RaeganClem2023.jpg?width=300',
    number: '8',
    name: 'Raegan Clem',
    position: 'Catcher',
    year: 'RS Freshman',
    hometown: 'Athens, AL',
  },
  {
    id: '8',
    image:
      'https://www.roarlions.com/images/2022/10/31/LillyWerling2023.jpg?width=300',
    number: '9',
    name: 'Lilly Werling',
    position: 'Infielder',
    year: 'Freshman',
    hometown: 'Jasper, AL',
  },
  {
    id: '9',
    image:
      'https://www.roarlions.com/images/2022/10/31/HavenKirby2023.jpg?width=300',
    number: '10',
    name: 'Haven Kirby',
    position: 'Infield',
    year: 'Junior',
    hometown: 'Elkmont, AL',
  },
  {
    id: '10',
    image:
      'https://www.roarlions.com/images/2022/10/31/RyleighBoyett2023.jpg?width=300',
    number: '11',
    name: 'Ryleigh Boyett',
    position: 'Infield',
    year: 'Sophomore',
    hometown: 'Cookeville, TN',
  },
  {
    id: '11',
    image:
      'https://www.roarlions.com/images/2022/10/31/MariynWaterman2023.jpg?width=300',
    number: '13',
    name: 'Mariyn Waterman',
    position: 'Pitcher',
    year: 'Junior',
    hometown: 'Oakdale, CA',
  },
  {
    id: '12',
    image:
      'https://www.roarlions.com/images/2022/10/31/SidneyBevis2023.jpg?width=300',
    number: '14',
    name: 'Sydney Bevis',
    position: 'Outfielder',
    year: 'Junior',
    hometown: 'Florence, AL',
  },
  {
    id: '13',
    image:
      'https://www.roarlions.com/images/2022/10/31/ElenaEscobar2023.jpg?width=300',
    number: '15',
    name: 'Elena Escobar',
    position: 'Pitcher',
    year: 'Sophomore',
    hometown: 'Spring Hill, TN',
  },
  {
    id: '14',
    image:
      'https://www.roarlions.com/images/2022/10/31/HannahEmbry2023.jpg?width=300',
    number: '16',
    name: 'Hannah Embry',
    position: 'Pitcher',
    year: 'Junior',
    hometown: 'Vicksburg, MS',
  },
  {
    id: '15',
    image:
      'https://www.roarlions.com/images/2022/10/31/HolleyFiles2023.jpg?width=300',
    number: '17',
    name: 'Holley Files',
    position: 'Infield',
    year: 'Junior',
    hometown: 'Fayette, AL',
  },
  {
    id: '16',
    image:
      'https://www.roarlions.com/images/2022/10/31/JaidenFarnetti2023.jpg?width=300',
    number: '18',
    name: 'Jaiden Farnetti',
    position: 'Infielder',
    year: 'Junior',
    hometown: 'West Blocton, AL',
  },
  {
    id: '17',
    image:
      'https://www.roarlions.com/images/2022/10/31/BeccaBenton2023.jpg?width=300',
    number: '19',
    name: 'Becca Benton',
    position: 'Infielder',
    year: 'Freshman',
    hometown: 'Hayden, AL',
  },
  {
    id: '18',
    image:
      'https://www.roarlions.com/images/2022/10/31/SophieGolliver2023.jpg?width=300',
    number: '20',
    name: 'Sophie Golliver',
    position: 'Pitcher',
    year: 'Junior',
    hometown: 'Murfreesboro, TN',
  },
  {
    id: '19',
    image:
      'https://www.roarlions.com/images/2022/10/31/MaciBirdyshaw2023.jpg?width=300',
    number: '22',
    name: 'Maci Birdyshaw',
    position: 'Pitcher',
    year: 'Senior',
    hometown: 'Lawrenceburg, TN',
  },
  {
    id: '20',
    image:
      'https://www.roarlions.com/images/2022/10/31/GracePiotrowski2023.jpg?width=300',
    number: '23',
    name: 'Grace Piotrowski',
    position: 'Catcher',
    year: 'Junior',
    hometown: 'Tinley Park, IL',
  },
  {
    id: '21',
    image:
      'https://www.roarlions.com/images/2022/10/31/GracieBenton2023.jpg?width=300',
    number: '24',
    name: 'Gracie Benton',
    position: 'Utility',
    year: 'Junior',
    hometown: 'Hayden, AL',
  },
  {
    id: '22',
    image:
      'https://www.roarlions.com/images/2022/10/31/GeorgiaLand2023.jpg?width=300',
    number: '25',
    name: 'Georgia Land',
    position: 'Catcher',
    year: 'Senior',
    hometown: 'Lawrenceburg, TN',
  },
  {
    id: '23',
    image:
      'https://www.roarlions.com/images/2022/10/31/DanielleTaitt2023.jpg?width=300',
    number: '26',
    name: 'Danielle Taitt',
    position: 'Pitcher',
    year: 'Junior',
    hometown: 'Snellville, GA',
  },
  {
    id: '24',
    image:
      'https://www.roarlions.com/images/2022/10/31/TaylorBrown2023.jpg?width=300',
    number: '30',
    name: 'Taylor Brown',
    position: '3B',
    year: 'Senior',
    hometown: 'Florence, AL',
  },
];
