export const colors = {
  red: '#FF0000',
  svgBlack: '#000000',
  twitterColor: '#55ACEE',
  greySmall: '#969696',
  borderPostColor: '#E9E9EA',
  inActiveColor: '#B2B2B2',
  buttonPrimary: '#592B81',
  buttonPrimaryTextColor: '#fff',
  receiptColorText: '#9C9C9C',
  backgroundColor: '#F9F9F9',
  greyishColor: '#949494',
  dangerColor: '#d9534f',
  placeholderColor: '#9B9B9B',
  inputFieldBackgroundColor: '#F5F5F5',
  inputFieldTextColor: 'rgba(0,0,0,0.7)',
  buttonGreenColor: '#377D22',
  horizontalColor: '#C4C4C4',
  black: '#000',
  borderColor: '#C6C6C6',
  borderGreen: '#377D22',
  printButtonColor: '#696969',
  borderRed: '#A90000',
  pickleContainerColor: '#EBEBEB',
  cancelOrderColor: '#7F170E',
  compeleteOrderColor: '#377D22',
  modalSubmitGreen: '#42AD00',
  modalDangerColor1: '#ECDCDB',
  modalDangerColor2: '#8A4743',
  dangerColorSmallButtonBackgoround3: '#E08C87',
  completeOrderGreenColor1: '#E1EBDE',
  completeOrderGreenColor2: '#9DBD94',
  charLimitExceedColor: '#990606',
  editVenueColor: 'rgba(255,255,255,1)',

  //clubmogo
  themeBackground: `#204692`,
  primaryColor: `#365da0`,
  gray: `#a5a5a9`,
  gray1: '#777677',
  gray2: `#c6c8ca`,
  gray3: `#bcbdbf`,
  gray4: '#C4C4C4',
  gray5: '#939597',
  gray6: `#444444`,
  gray7: `#434444`,
  gray8: `#d6d6d8`,
  gray9: '#C7C8CA',
  gray10: '#BCBEC0',
  gray11: '#E6E7E8',
  gray12: '#F5F5F5',
  grayPendingData: '#EEEEEE',
  red: 'red',
  red2: '#CD3224',
  greenalertColor: '#208F0C',
  lightGreenToast: '#9FDCBA',
  lightBlueToast: '#BED5F5',
  darkBlueToast: '#1C5FBA',
  lightYellowToast: '#FFE8C3',
  darkYellowToast: '#BA7B14',
  lightRedToast: '#FFCFCB',
  lightTransparent: 'rgba(0, 0, 0, 0.5)',
  darkGreenToast: '#268753',
  bluealertColor: '#3C60A6',
  redAlertColor: '#A41306',
  pink: '#FF5252',
  white: `#FFFFFF`,
  black: '#000',
  lightBlue: '#28A9E1',
  iconColor: '#D1D2D4',
  greyBackground: '#f5f5f5',
  outOfStockColor: '#ed6d67',
  goldenColor: '#E2901B',
  timerBackGrondColor: '#F0F1F6',
  greyColorSmall: '#787878',
  pointBackgroundColor: 'rgba(89, 43, 129, 0.1)',
};

export const customLables = {
  ok: 'OK',
  login: 'Log In',
  profile: 'Profile',
  matthewRhodes: 'Matthew Rhodes',
  upcomingEvents: 'Upcoming Events',
  teams: 'Teams',
  footballTeam: 'Football Team',
  or: 'Or',
  phoneNumber: 'Phone Number',
  password: 'Password',
  createAccount: 'Create Account',
  lastName: 'Last Name',
  firstName: 'First Name',
  phoneNumber: 'Phone Number',
  emailAddress: 'Email Address',
  optOutOfTextMessagesFromUNA: ' Opt Out Of Text Messages From UNA',
  optOutOfEmailsFromUNA: ' Opt Out Of Emails From UNA',
  logOut: 'Log Out',
  deleteAccount: 'Delete Account',
  signUp: '   Sign Up',
  email: 'Email',
  emailError: 'Email is not valid',
  phoneError: 'Phone Number is not valid',
  createNewAccount: 'Create Your Account',
  confirmPassword: 'Confirm Password',
  alreadyHaveAAccount: 'Already have a account? ',
  changePassword: 'Change Password',
  newPassword: 'New Password',
  forgotPassword: 'Forgot Password',
  enterYourPhoneNumberToResetYourPassword:
    'Enter your phone number to reset your password',
  enterDigitCode: 'Enter 6 Digit Code',
  enterCodeSentToYourDeviceToResetYourPassword:
    'Enter code sent to your device to reset your password',
  submit: 'Submit',
  forgotPasswordLink: 'Forgot Password?',
  resetYourPassword: 'Reset Your Password',
  sendCode: 'Send Code',
  TBA: 'TBA',
  enterNewPassword: 'Enter New Password',
  confirmNewPassword: 'Confirm New Password',
  changePassword: 'Change Password',
  verifyCode: 'Verify Code',
};

export const fontSize = {
  iconSize: 70,
  title: 32,
  h1: 30,
  h2: 28,
  h3: 26,
  h4: 25,
  h5: 24,
  h6: 22,
  xxlarge: 20,
  xlarge: 19,
  large: 18,
  medium: 17,
  average: 18.5,
  normal: 16,
  small: 15,
  xsmall: 14,
  xxsmall: 13,
  tiny: 12,
  xtiny: 11,
  xxtiny: 10,
  xxxtiny: 9,
  xxxtinyH: 9.5,
  big: 20,
  xbig: 27,
  xxbig: 29,
  smmlest: 8,
  vSmall: 7,
  vvSmallh: 6.5,
  vvSmall: 6,
  vvvSmall: 5,
};
export const fontFamily = {
  regular: 'Saira-Regular',
  semiBold: 'Saira-SemiBold',
  bold: 'Saira-Bold',
  extraBold: 'Saira-ExtraBold',
  medium: 'Saira-Medium',
  thin: 'Saira-Thin',
  italic: 'Saira-Italic',
  black: 'Saira-Black',
};

export const devicesWidth = {
  iphone_6_6s_7_8_X: '375',
  iphone_5s_SE: '320',
  iphone_6Plus_6sPlus_7Plus_8Plus: '414',
  iPad: '768',
  iPad_10dot5: '834',
  iPad_12dot9: '1024',
  androidsmall: '400',
  android3XL: '560',
};
export const deviceHeight = {
  iphone_6_6s_7_8: '667',
  ipad: '1024',
  iPad_12dot9: '1366',
  iPad_10dot5: '1112',
  iphone_6Plus_6sPlus_7Plus_8Plus: '736',
  iphoneX: '812',
  iphone_5s_SE: '568',
};
